# https://taskfile.dev

version: "3"

interval: 100ms

vars:
  GREETING: Hello, World!

tasks:
  tools:
    cmds:
      - go install github.com/go-task/task/v3/cmd/task@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - test -f code/go/site/twcli || wget -O code/go/site/twcli https://github.com/dobicinaitis/tailwind-cli-extra/releases/download/v1.7.20/tailwindcss-extra-linux-x64
      - chmod +x code/go/site/twcli

  tsbuild:
    sources:
      - "**/package.json"
      - "**/*.ts"
    generates:
      - "bundles/**/*"
    cmds:
      - go run code/go/cmd/tsbuild/main.go
      - cp -r bundles/datastar.js* code/go/site/static/js/

  css:
    dir: code/go/site
    sources:
      - "**/*.templ"
      - "**/*.md"
    generates:
      - "static/css/site.css"

    cmds:
      - ./twcli build -o static/css/site.css

  templ:
    env:
      TEMPL_EXPERIMENT: rawgo
    generates:
      - "**/*_templ.go"
    sources:
      - "**/*.templ"
    cmds:
      - templ generate .

  kill:
    method: none
    cmds:
      - fuser -k 4222/tcp > /dev/null 2>&1 || true

  site:
    desc: build and run site
    sources:
      - code/go/**/*.templ
      - code/go/**/*.go
      - code/go/**/*.md
      - code/go/site/static/**/*
    generates:
      - ./datastar-website
    deps:
      - kill
      - tsbuild
      - templ
      - css

    cmds:
      - go mod tidy
      - go build -o ./datastar-website code/go/cmd/site/main.go
      - ./datastar-website

  default:
    cmds:
      - task: site
