// Code generated by qtc from "consts_php.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line code/go/tsbuild/consts_php.qtpl:1
package tsbuild

//line code/go/tsbuild/consts_php.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line code/go/tsbuild/consts_php.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line code/go/tsbuild/consts_php.qtpl:1
func streamphpConstants(qw422016 *qt422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:1
	qw422016.N().S(`<?php

namespace starfederation\datastar;

use starfederation\datastar\enums\FragmentMergeMode;

/**
 * This class is auto-generated, do not modify.
 */
class Constants
{
    public const DatastarKey = '`)
//line code/go/tsbuild/consts_php.qtpl:13
	qw422016.E().S(data.DatastarKey)
//line code/go/tsbuild/consts_php.qtpl:13
	qw422016.N().S(`';
    public const Version = '`)
//line code/go/tsbuild/consts_php.qtpl:14
	qw422016.E().S(data.Version)
//line code/go/tsbuild/consts_php.qtpl:14
	qw422016.N().S(`';
    public const VersionClientByteSize = `)
//line code/go/tsbuild/consts_php.qtpl:15
	qw422016.N().D(data.VersionClientByteSize)
//line code/go/tsbuild/consts_php.qtpl:15
	qw422016.N().S(`;
    public const VersionClientByteSizeGzip = `)
//line code/go/tsbuild/consts_php.qtpl:16
	qw422016.N().D(data.VersionClientByteSizeGzip)
//line code/go/tsbuild/consts_php.qtpl:16
	qw422016.N().S(`;
    public const DefaultSettleDuration = `)
//line code/go/tsbuild/consts_php.qtpl:17
	qw422016.N().D(durationToMs(data.DefaultSettleDuration))
//line code/go/tsbuild/consts_php.qtpl:17
	qw422016.N().S(`;
    public const DefaultSSERetryDuration = `)
//line code/go/tsbuild/consts_php.qtpl:18
	qw422016.N().D(durationToMs(data.DefaultSSERetryDuration))
//line code/go/tsbuild/consts_php.qtpl:18
	qw422016.N().S(`;
    public const DefaultUseViewTransitions = `)
//line code/go/tsbuild/consts_php.qtpl:19
	qw422016.E().V(data.DefaultUseViewTransitions)
//line code/go/tsbuild/consts_php.qtpl:19
	qw422016.N().S(`;
    public const DefaultOnlyIfMissing = `)
//line code/go/tsbuild/consts_php.qtpl:20
	qw422016.E().V(data.DefaultOnlyIfMissing)
//line code/go/tsbuild/consts_php.qtpl:20
	qw422016.N().S(`;
`)
//line code/go/tsbuild/consts_php.qtpl:21
	for _, enum := range data.Enums {
//line code/go/tsbuild/consts_php.qtpl:22
		if enum.Default != nil {
//line code/go/tsbuild/consts_php.qtpl:22
			qw422016.N().S(`    public const Default`)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.E().S(enum.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.N().S(` = `)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.E().S(enum.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.N().S(`::`)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.E().S(enum.Default.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:23
			qw422016.N().S(`;
`)
//line code/go/tsbuild/consts_php.qtpl:24
		}
//line code/go/tsbuild/consts_php.qtpl:25
	}
//line code/go/tsbuild/consts_php.qtpl:26
	for _, literal := range data.DatalineLiterals {
//line code/go/tsbuild/consts_php.qtpl:26
		qw422016.N().S(`    public const `)
//line code/go/tsbuild/consts_php.qtpl:27
		qw422016.E().S(literal.Pascal)
//line code/go/tsbuild/consts_php.qtpl:27
		qw422016.N().S(`DatalineLiteral = '`)
//line code/go/tsbuild/consts_php.qtpl:27
		qw422016.E().S(literal.Camel)
//line code/go/tsbuild/consts_php.qtpl:27
		qw422016.N().S(` ';
`)
//line code/go/tsbuild/consts_php.qtpl:28
	}
//line code/go/tsbuild/consts_php.qtpl:28
	qw422016.N().S(`}
`)
//line code/go/tsbuild/consts_php.qtpl:30
}

//line code/go/tsbuild/consts_php.qtpl:30
func writephpConstants(qq422016 qtio422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line code/go/tsbuild/consts_php.qtpl:30
	streamphpConstants(qw422016, data)
//line code/go/tsbuild/consts_php.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line code/go/tsbuild/consts_php.qtpl:30
}

//line code/go/tsbuild/consts_php.qtpl:30
func phpConstants(data *ConstTemplateData) string {
//line code/go/tsbuild/consts_php.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line code/go/tsbuild/consts_php.qtpl:30
	writephpConstants(qb422016, data)
//line code/go/tsbuild/consts_php.qtpl:30
	qs422016 := string(qb422016.B)
//line code/go/tsbuild/consts_php.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line code/go/tsbuild/consts_php.qtpl:30
	return qs422016
//line code/go/tsbuild/consts_php.qtpl:30
}

//line code/go/tsbuild/consts_php.qtpl:32
func streamphpEventType(qw422016 *qt422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:32
	qw422016.N().S(`<?php

namespace starfederation\datastar\enums;

/**
 * This class is auto-generated, do not modify.
 */
enum EventType: string
{
`)
//line code/go/tsbuild/consts_php.qtpl:42
	for _, enum := range data.Enums {
//line code/go/tsbuild/consts_php.qtpl:43
		if enum.Name.Pascal == "EventType" {
//line code/go/tsbuild/consts_php.qtpl:44
			for _, entry := range enum.Values {
//line code/go/tsbuild/consts_php.qtpl:44
				qw422016.N().S(`    // `)
//line code/go/tsbuild/consts_php.qtpl:45
				qw422016.E().S(entry.Description)
//line code/go/tsbuild/consts_php.qtpl:45
				qw422016.N().S(`
    case `)
//line code/go/tsbuild/consts_php.qtpl:46
				qw422016.E().S(entry.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:46
				qw422016.N().S(` = '`)
//line code/go/tsbuild/consts_php.qtpl:46
				qw422016.E().S(entry.Value)
//line code/go/tsbuild/consts_php.qtpl:46
				qw422016.N().S(`';

`)
//line code/go/tsbuild/consts_php.qtpl:48
			}
//line code/go/tsbuild/consts_php.qtpl:49
		}
//line code/go/tsbuild/consts_php.qtpl:50
	}
//line code/go/tsbuild/consts_php.qtpl:50
	qw422016.N().S(`}
`)
//line code/go/tsbuild/consts_php.qtpl:52
}

//line code/go/tsbuild/consts_php.qtpl:52
func writephpEventType(qq422016 qtio422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:52
	qw422016 := qt422016.AcquireWriter(qq422016)
//line code/go/tsbuild/consts_php.qtpl:52
	streamphpEventType(qw422016, data)
//line code/go/tsbuild/consts_php.qtpl:52
	qt422016.ReleaseWriter(qw422016)
//line code/go/tsbuild/consts_php.qtpl:52
}

//line code/go/tsbuild/consts_php.qtpl:52
func phpEventType(data *ConstTemplateData) string {
//line code/go/tsbuild/consts_php.qtpl:52
	qb422016 := qt422016.AcquireByteBuffer()
//line code/go/tsbuild/consts_php.qtpl:52
	writephpEventType(qb422016, data)
//line code/go/tsbuild/consts_php.qtpl:52
	qs422016 := string(qb422016.B)
//line code/go/tsbuild/consts_php.qtpl:52
	qt422016.ReleaseByteBuffer(qb422016)
//line code/go/tsbuild/consts_php.qtpl:52
	return qs422016
//line code/go/tsbuild/consts_php.qtpl:52
}

//line code/go/tsbuild/consts_php.qtpl:54
func streamphpFragmentMergeMode(qw422016 *qt422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:54
	qw422016.N().S(`<?php

namespace starfederation\datastar\enums;

/**
 * This class is auto-generated, do not modify.
 */
enum FragmentMergeMode: string
{
`)
//line code/go/tsbuild/consts_php.qtpl:64
	for _, enum := range data.Enums {
//line code/go/tsbuild/consts_php.qtpl:65
		if enum.Name.Pascal == "FragmentMergeMode" {
//line code/go/tsbuild/consts_php.qtpl:66
			for _, entry := range enum.Values {
//line code/go/tsbuild/consts_php.qtpl:66
				qw422016.N().S(`    // `)
//line code/go/tsbuild/consts_php.qtpl:67
				qw422016.E().S(entry.Description)
//line code/go/tsbuild/consts_php.qtpl:67
				qw422016.N().S(`
    case `)
//line code/go/tsbuild/consts_php.qtpl:68
				qw422016.E().S(entry.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:68
				qw422016.N().S(` = '`)
//line code/go/tsbuild/consts_php.qtpl:68
				qw422016.E().S(entry.Value)
//line code/go/tsbuild/consts_php.qtpl:68
				qw422016.N().S(`';

`)
//line code/go/tsbuild/consts_php.qtpl:70
			}
//line code/go/tsbuild/consts_php.qtpl:71
		}
//line code/go/tsbuild/consts_php.qtpl:72
	}
//line code/go/tsbuild/consts_php.qtpl:72
	qw422016.N().S(`}
`)
//line code/go/tsbuild/consts_php.qtpl:74
}

//line code/go/tsbuild/consts_php.qtpl:74
func writephpFragmentMergeMode(qq422016 qtio422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:74
	qw422016 := qt422016.AcquireWriter(qq422016)
//line code/go/tsbuild/consts_php.qtpl:74
	streamphpFragmentMergeMode(qw422016, data)
//line code/go/tsbuild/consts_php.qtpl:74
	qt422016.ReleaseWriter(qw422016)
//line code/go/tsbuild/consts_php.qtpl:74
}

//line code/go/tsbuild/consts_php.qtpl:74
func phpFragmentMergeMode(data *ConstTemplateData) string {
//line code/go/tsbuild/consts_php.qtpl:74
	qb422016 := qt422016.AcquireByteBuffer()
//line code/go/tsbuild/consts_php.qtpl:74
	writephpFragmentMergeMode(qb422016, data)
//line code/go/tsbuild/consts_php.qtpl:74
	qs422016 := string(qb422016.B)
//line code/go/tsbuild/consts_php.qtpl:74
	qt422016.ReleaseByteBuffer(qb422016)
//line code/go/tsbuild/consts_php.qtpl:74
	return qs422016
//line code/go/tsbuild/consts_php.qtpl:74
}

//line code/go/tsbuild/consts_php.qtpl:76
func streamphpConsoleMode(qw422016 *qt422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:76
	qw422016.N().S(`<?php

namespace starfederation\datastar\enums;

/**
 * This class is auto-generated, do not modify.
 */
enum ConsoleMode: string
{
`)
//line code/go/tsbuild/consts_php.qtpl:86
	for _, enum := range data.Enums {
//line code/go/tsbuild/consts_php.qtpl:87
		if enum.Name.Pascal == "ConsoleMode" {
//line code/go/tsbuild/consts_php.qtpl:88
			for _, entry := range enum.Values {
//line code/go/tsbuild/consts_php.qtpl:88
				qw422016.N().S(`    // `)
//line code/go/tsbuild/consts_php.qtpl:89
				qw422016.E().S(entry.Description)
//line code/go/tsbuild/consts_php.qtpl:89
				qw422016.N().S(`
    case `)
//line code/go/tsbuild/consts_php.qtpl:90
				qw422016.E().S(entry.Name.Pascal)
//line code/go/tsbuild/consts_php.qtpl:90
				qw422016.N().S(` = '`)
//line code/go/tsbuild/consts_php.qtpl:90
				qw422016.E().S(entry.Value)
//line code/go/tsbuild/consts_php.qtpl:90
				qw422016.N().S(`';

`)
//line code/go/tsbuild/consts_php.qtpl:92
			}
//line code/go/tsbuild/consts_php.qtpl:93
		}
//line code/go/tsbuild/consts_php.qtpl:94
	}
//line code/go/tsbuild/consts_php.qtpl:94
	qw422016.N().S(`}
`)
//line code/go/tsbuild/consts_php.qtpl:96
}

//line code/go/tsbuild/consts_php.qtpl:96
func writephpConsoleMode(qq422016 qtio422016.Writer, data *ConstTemplateData) {
//line code/go/tsbuild/consts_php.qtpl:96
	qw422016 := qt422016.AcquireWriter(qq422016)
//line code/go/tsbuild/consts_php.qtpl:96
	streamphpConsoleMode(qw422016, data)
//line code/go/tsbuild/consts_php.qtpl:96
	qt422016.ReleaseWriter(qw422016)
//line code/go/tsbuild/consts_php.qtpl:96
}

//line code/go/tsbuild/consts_php.qtpl:96
func phpConsoleMode(data *ConstTemplateData) string {
//line code/go/tsbuild/consts_php.qtpl:96
	qb422016 := qt422016.AcquireByteBuffer()
//line code/go/tsbuild/consts_php.qtpl:96
	writephpConsoleMode(qb422016, data)
//line code/go/tsbuild/consts_php.qtpl:96
	qs422016 := string(qb422016.B)
//line code/go/tsbuild/consts_php.qtpl:96
	qt422016.ReleaseByteBuffer(qb422016)
//line code/go/tsbuild/consts_php.qtpl:96
	return qs422016
//line code/go/tsbuild/consts_php.qtpl:96
}
