<?php

namespace starfederation\datastar;

use starfederation\datastar\enums\FragmentMergeMode;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
class Constants
{
    public const DatastarKey = 'datastar';
    public const Version = '0.20.0';
    public const VersionClientByteSize = 42950;
    public const VersionClientByteSizeGzip = 14706;
    public const DefaultSettleDuration = 300;
    public const DefaultSseRetryDuration = 1000;
    public const DefaultUseViewTransitions = false;
    public const DefaultOnlyIfMissing = false;
    public const DefaultAutoRemoveScript = true;
    public const DefaultCustomEventCancelable = true;
    public const DefaultCustomEventComposed = true;
    public const DefaultCustomEventBubbles = true;
    public const DefaultCustomEventSelector = 'document';
    public const DefaultCustomEventDetailJson = '{}';
    public const DefaultFragmentMergeMode = FragmentMergeMode::Morph;
    public const SelectorDatalineLiteral = 'selector ';
    public const MergeModeDatalineLiteral = 'mergeMode ';
    public const SettleDurationDatalineLiteral = 'settleDuration ';
    public const FragmentDatalineLiteral = 'fragment ';
    public const UseViewTransitionDatalineLiteral = 'useViewTransition ';
    public const StoreDatalineLiteral = 'store ';
    public const OnlyIfMissingDatalineLiteral = 'onlyIfMissing ';
    public const UrlDatalineLiteral = 'url ';
    public const PathsDatalineLiteral = 'paths ';
    public const ScriptDatalineLiteral = 'script ';
    public const AutoRemoveScriptDatalineLiteral = 'autoRemoveScript ';
    public const EventNameDatalineLiteral = 'eventName ';
    public const CancelableDatalineLiteral = 'cancelable ';
    public const ComposedDatalineLiteral = 'composed ';
    public const BubblesDatalineLiteral = 'bubbles ';
    public const DetailJsonDatalineLiteral = 'detailJson ';
}