// this file is autogenerated by task tsbuild

export const version = "1.0.0-beta.1";
export const versionClientByteSize = 43972;
export const versionClientByteSizeGzip = 15021;
export const versionClientByteSizeGzipHuman = ";

export const defaultSettleTime = 300 * 1000;
export const defaultSettleTime = 1000 * 1000;
export const defaultSettleTime = "morph";