<?php

namespace starfederation\datastar\enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
enum EventType: string
{
    // An event dealing with HTML fragments.
    case MergeFragments = 'datastar-merge-fragments';

    // An event dealing with fine grain signals.
    case MergeSignals = 'datastar-merge-signals';

    // An event dealing with removing elements from the DOM
    case RemoveFragments = 'datastar-remove-fragments';

    // An event dealing with removing signals
    case RemoveSignals = 'datastar-remove-signals';

    // An event dealing with executing JavaScript in the browser.
    case ExecuteJs = 'datastar-execute-js';

}