<?php

namespace starfederation\datastar\enums;

/**
 * This is auto-generated by Datastar. DO NOT EDIT.
 */
enum EventType: string
{
    // An event dealing with HTML fragments.
    case MergeFragments = 'datastar-merge-fragments';

    // An event dealing with fine grain signals.
    case MergeStore = 'datastar-merge-store';

    // An event dealing with removing elements from the DOM
    case RemoveFragments = 'datastar-remove-fragments';

    // An event dealing with removing signals from the store.
    case RemoveFromStore = 'datastar-remove-from-store';

    // An event dealing with redirecting the browser.
    case Redirect = 'datastar-redirect';

    // An event dealing to execute functions in the browser.
    case ExecuteJs = 'datastar-execute-js';

    // An event dealing with custom events.
    case DispatchCustomEvent = 'datastar-dispatch-custom-event';

}